FROM node:22-alpine AS builder

WORKDIR /app

ENV NODE_ENV=development

COPY . .
RUN npm install
RUN npx quasar build

FROM nginx:1.27-alpine

COPY --from=builder /app/dist/spa /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80