"""add pdf metadata to documents

Revision ID: 67f1c3c8ffa8
Revises: f12da82143d5
Create Date: 2026-05-02 06:51:10.278129

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '67f1c3c8ffa8'
down_revision: Union[str, None] = 'f12da82143d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('pdf_storage_key', sa.String(length=500), nullable=True))
    op.add_column('documents', sa.Column('pdf_generated_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'pdf_generated_at')
    op.drop_column('documents', 'pdf_storage_key')
    # ### end Alembic commands ###
