"""add kind column to documents

Revision ID: e7e7d51436f6
Revises: 67f1c3c8ffa8
Create Date: 2026-05-02 11:01:48.474294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7e7d51436f6'
down_revision: Union[str, None] = '67f1c3c8ffa8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('kind', sa.String(length=32), server_default='document', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'kind')
    # ### end Alembic commands ###
